### ISSUE TITLE
你好 有个关于学习的问题想请教一下~

### ISSUE THREAD

**Issue by authhwang** [Desgard/iOS-Source-Probe#7]
瓜哥你好~我想问下对于你而言 你觉得iOS看官方文档(例如guide)和看源码哪个优先度高一点？(或者说学得更多一点？)

**Comment by Desgard** [comment]
个人感觉文档讲的较为生僻，有很多细节理解起来需要很多的基础，要不断的检索。。一般是先大体过一遍文档，才开始看源码继续学习。优先度没有多明确，结合起来一起学习可能理解的会透彻一点。

**Comment by authhwang** [comment]
原来如此~谢谢瓜哥~

**Comment by authhwang** [comment]
原来如此~谢谢瓜哥
